<option value="" <?php echo esc_attr( $item->fa_icon ) == "" ? 'selected' : ''; ?>></option>
<option value="fa-adjust" <?php echo esc_attr( $item->fa_icon ) == "fa-adjust" ? 'selected' : ''; ?>>adjust</option>
<option value="fa-adn" <?php echo esc_attr( $item->fa_icon ) == "fa-adn" ? 'selected' : ''; ?>>adn</option>
<option value="fa-align-center" <?php echo esc_attr( $item->fa_icon ) == "fa-align-center" ? 'selected' : ''; ?>>align-center</option>
<option value="fa-align-justify" <?php echo esc_attr( $item->fa_icon ) == "fa-align-justify" ? 'selected' : ''; ?>>align-justify</option>
<option value="fa-align-left" <?php echo esc_attr( $item->fa_icon ) == "fa-align-left" ? 'selected' : ''; ?>>align-left</option>
<option value="fa-align-right" <?php echo esc_attr( $item->fa_icon ) == "fa-align-right" ? 'selected' : ''; ?>>align-right</option>
<option value="fa-ambulance" <?php echo esc_attr( $item->fa_icon ) == "fa-ambulance" ? 'selected' : ''; ?>>ambulance</option>
<option value="fa-anchor" <?php echo esc_attr( $item->fa_icon ) == "fa-anchor" ? 'selected' : ''; ?>>anchor</option>
<option value="fa-android" <?php echo esc_attr( $item->fa_icon ) == "fa-android" ? 'selected' : ''; ?>>android</option>
<option value="fa-angellist" <?php echo esc_attr( $item->fa_icon ) == "fa-angellist" ? 'selected' : ''; ?>>angellist</option>
<option value="fa-angle-double-down" <?php echo esc_attr( $item->fa_icon ) == "fa-angle-double-down" ? 'selected' : ''; ?>>angle-double-down</option>
<option value="fa-angle-double-left" <?php echo esc_attr( $item->fa_icon ) == "fa-angle-double-left" ? 'selected' : ''; ?>>angle-double-left</option>
<option value="fa-angle-double-right" <?php echo esc_attr( $item->fa_icon ) == "fa-angle-double-right" ? 'selected' : ''; ?>>angle-double-right</option>
<option value="fa-angle-double-up" <?php echo esc_attr( $item->fa_icon ) == "fa-angle-double-up" ? 'selected' : ''; ?>>angle-double-up</option>
<option value="fa-angle-down" <?php echo esc_attr( $item->fa_icon ) == "fa-angle-down" ? 'selected' : ''; ?>>angle-down</option>
<option value="fa-angle-left" <?php echo esc_attr( $item->fa_icon ) == "fa-angle-left" ? 'selected' : ''; ?>>angle-left</option>
<option value="fa-angle-right" <?php echo esc_attr( $item->fa_icon ) == "fa-angle-right" ? 'selected' : ''; ?>>angle-right</option>
<option value="fa-angle-up" <?php echo esc_attr( $item->fa_icon ) == "fa-angle-up" ? 'selected' : ''; ?>>angle-up</option>
<option value="fa-apple" <?php echo esc_attr( $item->fa_icon ) == "fa-apple" ? 'selected' : ''; ?>>apple</option>
<option value="fa-archive" <?php echo esc_attr( $item->fa_icon ) == "fa-archive" ? 'selected' : ''; ?>>archive</option>
<option value="fa-area-chart" <?php echo esc_attr( $item->fa_icon ) == "fa-area-chart" ? 'selected' : ''; ?>>area-chart</option>
<option value="fa-arrow-circle-down" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-circle-down" ? 'selected' : ''; ?>>arrow-circle-down</option>
<option value="fa-arrow-circle-left" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-circle-left" ? 'selected' : ''; ?>>arrow-circle-left</option>
<option value="fa-arrow-circle-o-down" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-circle-o-down" ? 'selected' : ''; ?>>arrow-circle-o-down</option>
<option value="fa-arrow-circle-o-left" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-circle-o-left" ? 'selected' : ''; ?>>arrow-circle-o-left</option>
<option value="fa-arrow-circle-o-right" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-circle-o-right" ? 'selected' : ''; ?>>arrow-circle-o-right</option>
<option value="fa-arrow-circle-o-up" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-circle-o-up" ? 'selected' : ''; ?>>arrow-circle-o-up</option>
<option value="fa-arrow-circle-right" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-circle-right" ? 'selected' : ''; ?>>arrow-circle-right</option>
<option value="fa-arrow-circle-up" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-circle-up" ? 'selected' : ''; ?>>arrow-circle-up</option>
<option value="fa-arrow-down" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-down" ? 'selected' : ''; ?>>arrow-down</option>
<option value="fa-arrow-left" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-left" ? 'selected' : ''; ?>>arrow-left</option>
<option value="fa-arrow-right" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-right" ? 'selected' : ''; ?>>arrow-right</option>
<option value="fa-arrow-up" <?php echo esc_attr( $item->fa_icon ) == "fa-arrow-up" ? 'selected' : ''; ?>>arrow-up</option>
<option value="fa-arrows" <?php echo esc_attr( $item->fa_icon ) == "fa-arrows" ? 'selected' : ''; ?>>arrows</option>
<option value="fa-arrows-alt" <?php echo esc_attr( $item->fa_icon ) == "fa-arrows-alt" ? 'selected' : ''; ?>>arrows-alt</option>
<option value="fa-arrows-h" <?php echo esc_attr( $item->fa_icon ) == "fa-arrows-h" ? 'selected' : ''; ?>>arrows-h</option>
<option value="fa-arrows-v" <?php echo esc_attr( $item->fa_icon ) == "fa-arrows-v" ? 'selected' : ''; ?>>arrows-v</option>
<option value="fa-asterisk" <?php echo esc_attr( $item->fa_icon ) == "fa-asterisk" ? 'selected' : ''; ?>>asterisk</option>
<option value="fa-at" <?php echo esc_attr( $item->fa_icon ) == "fa-at" ? 'selected' : ''; ?>>at</option>
<option value="fa-automobile" <?php echo esc_attr( $item->fa_icon ) == "fa-automobile" ? 'selected' : ''; ?>>automobile</option>
<option value="fa-backward" <?php echo esc_attr( $item->fa_icon ) == "fa-backward" ? 'selected' : ''; ?>>backward</option>
<option value="fa-ban" <?php echo esc_attr( $item->fa_icon ) == "fa-ban" ? 'selected' : ''; ?>>ban</option>
<option value="fa-bank" <?php echo esc_attr( $item->fa_icon ) == "fa-bank" ? 'selected' : ''; ?>>bank</option>
<option value="fa-bar-chart" <?php echo esc_attr( $item->fa_icon ) == "fa-bar-chart" ? 'selected' : ''; ?>>bar-chart</option>
<option value="fa-bar-chart-o" <?php echo esc_attr( $item->fa_icon ) == "fa-bar-chart-o" ? 'selected' : ''; ?>>bar-chart-o</option>
<option value="fa-barcode" <?php echo esc_attr( $item->fa_icon ) == "fa-barcode" ? 'selected' : ''; ?>>barcode</option>
<option value="fa-bars" <?php echo esc_attr( $item->fa_icon ) == "fa-bars" ? 'selected' : ''; ?>>bars</option>
<option value="fa-beer" <?php echo esc_attr( $item->fa_icon ) == "fa-beer" ? 'selected' : ''; ?>>beer</option>
<option value="fa-behance" <?php echo esc_attr( $item->fa_icon ) == "fa-behance" ? 'selected' : ''; ?>>behance</option>
<option value="fa-behance-square" <?php echo esc_attr( $item->fa_icon ) == "fa-behance-square" ? 'selected' : ''; ?>>behance-square</option>
<option value="fa-bell" <?php echo esc_attr( $item->fa_icon ) == "fa-bell" ? 'selected' : ''; ?>>bell</option>
<option value="fa-bell-o" <?php echo esc_attr( $item->fa_icon ) == "fa-bell-o" ? 'selected' : ''; ?>>bell-o</option>
<option value="fa-bell-slash" <?php echo esc_attr( $item->fa_icon ) == "fa-bell-slash" ? 'selected' : ''; ?>>bell-slash</option>
<option value="fa-bell-slash-o" <?php echo esc_attr( $item->fa_icon ) == "fa-bell-slash-o" ? 'selected' : ''; ?>>bell-slash-o</option>
<option value="fa-bicycle" <?php echo esc_attr( $item->fa_icon ) == "fa-bicycle" ? 'selected' : ''; ?>>bicycle</option>
<option value="fa-binoculars" <?php echo esc_attr( $item->fa_icon ) == "fa-binoculars" ? 'selected' : ''; ?>>binoculars</option>
<option value="fa-birthday-cake" <?php echo esc_attr( $item->fa_icon ) == "fa-birthday-cake" ? 'selected' : ''; ?>>birthday-cake</option>
<option value="fa-bitbucket" <?php echo esc_attr( $item->fa_icon ) == "fa-bitbucket" ? 'selected' : ''; ?>>bitbucket</option>
<option value="fa-bitbucket-square" <?php echo esc_attr( $item->fa_icon ) == "fa-bitbucket-square" ? 'selected' : ''; ?>>bitbucket-square</option>
<option value="fa-bitcoin" <?php echo esc_attr( $item->fa_icon ) == "fa-bitcoin" ? 'selected' : ''; ?>>bitcoin</option>
<option value="fa-bold" <?php echo esc_attr( $item->fa_icon ) == "fa-bold" ? 'selected' : ''; ?>>bold</option>
<option value="fa-bolt" <?php echo esc_attr( $item->fa_icon ) == "fa-bolt" ? 'selected' : ''; ?>>bolt</option>
<option value="fa-bomb" <?php echo esc_attr( $item->fa_icon ) == "fa-bomb" ? 'selected' : ''; ?>>bomb</option>
<option value="fa-book" <?php echo esc_attr( $item->fa_icon ) == "fa-book" ? 'selected' : ''; ?>>book</option>
<option value="fa-bookmark" <?php echo esc_attr( $item->fa_icon ) == "fa-bookmark" ? 'selected' : ''; ?>>bookmark</option>
<option value="fa-bookmark-o" <?php echo esc_attr( $item->fa_icon ) == "fa-bookmark-o" ? 'selected' : ''; ?>>bookmark-o</option>
<option value="fa-briefcase" <?php echo esc_attr( $item->fa_icon ) == "fa-briefcase" ? 'selected' : ''; ?>>briefcase</option>
<option value="fa-btc" <?php echo esc_attr( $item->fa_icon ) == "fa-btc" ? 'selected' : ''; ?>>btc</option>
<option value="fa-bug" <?php echo esc_attr( $item->fa_icon ) == "fa-bug" ? 'selected' : ''; ?>>bug</option>
<option value="fa-building" <?php echo esc_attr( $item->fa_icon ) == "fa-building" ? 'selected' : ''; ?>>building</option>
<option value="fa-building-o" <?php echo esc_attr( $item->fa_icon ) == "fa-building-o" ? 'selected' : ''; ?>>building-o</option>
<option value="fa-bullhorn" <?php echo esc_attr( $item->fa_icon ) == "fa-bullhorn" ? 'selected' : ''; ?>>bullhorn</option>
<option value="fa-bullseye" <?php echo esc_attr( $item->fa_icon ) == "fa-bullseye" ? 'selected' : ''; ?>>bullseye</option>
<option value="fa-bus" <?php echo esc_attr( $item->fa_icon ) == "fa-bus" ? 'selected' : ''; ?>>bus</option>
<option value="fa-cab" <?php echo esc_attr( $item->fa_icon ) == "fa-cab" ? 'selected' : ''; ?>>cab</option>
<option value="fa-calculator" <?php echo esc_attr( $item->fa_icon ) == "fa-calculator" ? 'selected' : ''; ?>>calculator</option>
<option value="fa-calendar" <?php echo esc_attr( $item->fa_icon ) == "fa-calendar" ? 'selected' : ''; ?>>calendar</option>
<option value="fa-calendar-o" <?php echo esc_attr( $item->fa_icon ) == "fa-calendar-o" ? 'selected' : ''; ?>>calendar-o</option>
<option value="fa-camera" <?php echo esc_attr( $item->fa_icon ) == "fa-camera" ? 'selected' : ''; ?>>camera</option>
<option value="fa-camera-retro" <?php echo esc_attr( $item->fa_icon ) == "fa-camera-retro" ? 'selected' : ''; ?>>camera-retro</option>
<option value="fa-car" <?php echo esc_attr( $item->fa_icon ) == "fa-car" ? 'selected' : ''; ?>>car</option>
<option value="fa-caret-down" <?php echo esc_attr( $item->fa_icon ) == "fa-caret-down" ? 'selected' : ''; ?>>caret-down</option>
<option value="fa-caret-left" <?php echo esc_attr( $item->fa_icon ) == "fa-caret-left" ? 'selected' : ''; ?>>caret-left</option>
<option value="fa-caret-right" <?php echo esc_attr( $item->fa_icon ) == "fa-caret-right" ? 'selected' : ''; ?>>caret-right</option>
<option value="fa-caret-square-o-down" <?php echo esc_attr( $item->fa_icon ) == "fa-caret-square-o-down" ? 'selected' : ''; ?>>caret-square-o-down</option>
<option value="fa-caret-square-o-left" <?php echo esc_attr( $item->fa_icon ) == "fa-caret-square-o-left" ? 'selected' : ''; ?>>caret-square-o-left</option>
<option value="fa-caret-square-o-right" <?php echo esc_attr( $item->fa_icon ) == "fa-caret-square-o-right" ? 'selected' : ''; ?>>caret-square-o-right</option>
<option value="fa-caret-square-o-up" <?php echo esc_attr( $item->fa_icon ) == "fa-caret-square-o-up" ? 'selected' : ''; ?>>caret-square-o-up</option>
<option value="fa-caret-up" <?php echo esc_attr( $item->fa_icon ) == "fa-caret-up" ? 'selected' : ''; ?>>caret-up</option>
<option value="fa-cc" <?php echo esc_attr( $item->fa_icon ) == "fa-cc" ? 'selected' : ''; ?>>cc</option>
<option value="fa-cc-amex" <?php echo esc_attr( $item->fa_icon ) == "fa-cc-amex" ? 'selected' : ''; ?>>cc-amex</option>
<option value="fa-cc-discover" <?php echo esc_attr( $item->fa_icon ) == "fa-cc-discover" ? 'selected' : ''; ?>>cc-discover</option>
<option value="fa-cc-mastercard" <?php echo esc_attr( $item->fa_icon ) == "fa-cc-mastercard" ? 'selected' : ''; ?>>cc-mastercard</option>
<option value="fa-cc-paypal" <?php echo esc_attr( $item->fa_icon ) == "fa-cc-paypal" ? 'selected' : ''; ?>>cc-paypal</option>
<option value="fa-cc-stripe" <?php echo esc_attr( $item->fa_icon ) == "fa-cc-stripe" ? 'selected' : ''; ?>>cc-stripe</option>
<option value="fa-cc-visa" <?php echo esc_attr( $item->fa_icon ) == "fa-cc-visa" ? 'selected' : ''; ?>>cc-visa</option>
<option value="fa-certificate" <?php echo esc_attr( $item->fa_icon ) == "fa-certificate" ? 'selected' : ''; ?>>certificate</option>
<option value="fa-chain" <?php echo esc_attr( $item->fa_icon ) == "fa-chain" ? 'selected' : ''; ?>>chain</option>
<option value="fa-chain-broken" <?php echo esc_attr( $item->fa_icon ) == "fa-chain-broken" ? 'selected' : ''; ?>>chain-broken</option>
<option value="fa-check" <?php echo esc_attr( $item->fa_icon ) == "fa-check" ? 'selected' : ''; ?>>check</option>
<option value="fa-check-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-check-circle" ? 'selected' : ''; ?>>check-circle</option>
<option value="fa-check-circle-o" <?php echo esc_attr( $item->fa_icon ) == "fa-check-circle-o" ? 'selected' : ''; ?>>check-circle-o</option>
<option value="fa-check-square" <?php echo esc_attr( $item->fa_icon ) == "fa-check-square" ? 'selected' : ''; ?>>check-square</option>
<option value="fa-check-square-o" <?php echo esc_attr( $item->fa_icon ) == "fa-check-square-o" ? 'selected' : ''; ?>>check-square-o</option>
<option value="fa-chevron-circle-down" <?php echo esc_attr( $item->fa_icon ) == "fa-chevron-circle-down" ? 'selected' : ''; ?>>chevron-circle-down</option>
<option value="fa-chevron-circle-left" <?php echo esc_attr( $item->fa_icon ) == "fa-chevron-circle-left" ? 'selected' : ''; ?>>chevron-circle-left</option>
<option value="fa-chevron-circle-right" <?php echo esc_attr( $item->fa_icon ) == "fa-chevron-circle-right" ? 'selected' : ''; ?>>chevron-circle-right</option>
<option value="fa-chevron-circle-up" <?php echo esc_attr( $item->fa_icon ) == "fa-chevron-circle-up" ? 'selected' : ''; ?>>chevron-circle-up</option>
<option value="fa-chevron-down" <?php echo esc_attr( $item->fa_icon ) == "fa-chevron-down" ? 'selected' : ''; ?>>chevron-down</option>
<option value="fa-chevron-left" <?php echo esc_attr( $item->fa_icon ) == "fa-chevron-left" ? 'selected' : ''; ?>>chevron-left</option>
<option value="fa-chevron-right" <?php echo esc_attr( $item->fa_icon ) == "fa-chevron-right" ? 'selected' : ''; ?>>chevron-right</option>
<option value="fa-chevron-up" <?php echo esc_attr( $item->fa_icon ) == "fa-chevron-up" ? 'selected' : ''; ?>>chevron-up</option>
<option value="fa-child" <?php echo esc_attr( $item->fa_icon ) == "fa-child" ? 'selected' : ''; ?>>child</option>
<option value="fa-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-circle" ? 'selected' : ''; ?>>circle</option>
<option value="fa-circle-o" <?php echo esc_attr( $item->fa_icon ) == "fa-circle-o" ? 'selected' : ''; ?>>circle-o</option>
<option value="fa-circle-o-notch" <?php echo esc_attr( $item->fa_icon ) == "fa-circle-o-notch" ? 'selected' : ''; ?>>circle-o-notch</option>
<option value="fa-circle-thin" <?php echo esc_attr( $item->fa_icon ) == "fa-circle-thin" ? 'selected' : ''; ?>>circle-thin</option>
<option value="fa-clipboard" <?php echo esc_attr( $item->fa_icon ) == "fa-clipboard" ? 'selected' : ''; ?>>clipboard</option>
<option value="fa-clock-o" <?php echo esc_attr( $item->fa_icon ) == "fa-clock-o" ? 'selected' : ''; ?>>clock-o</option>
<option value="fa-close" <?php echo esc_attr( $item->fa_icon ) == "fa-close" ? 'selected' : ''; ?>>close</option>
<option value="fa-cloud" <?php echo esc_attr( $item->fa_icon ) == "fa-cloud" ? 'selected' : ''; ?>>cloud</option>
<option value="fa-cloud-download" <?php echo esc_attr( $item->fa_icon ) == "fa-cloud-download" ? 'selected' : ''; ?>>cloud-download</option>
<option value="fa-cloud-upload" <?php echo esc_attr( $item->fa_icon ) == "fa-cloud-upload" ? 'selected' : ''; ?>>cloud-upload</option>
<option value="fa-cny" <?php echo esc_attr( $item->fa_icon ) == "fa-cny" ? 'selected' : ''; ?>>cny</option>
<option value="fa-code" <?php echo esc_attr( $item->fa_icon ) == "fa-code" ? 'selected' : ''; ?>>code</option>
<option value="fa-code-fork" <?php echo esc_attr( $item->fa_icon ) == "fa-code-fork" ? 'selected' : ''; ?>>code-fork</option>
<option value="fa-codepen" <?php echo esc_attr( $item->fa_icon ) == "fa-codepen" ? 'selected' : ''; ?>>codepen</option>
<option value="fa-coffee" <?php echo esc_attr( $item->fa_icon ) == "fa-coffee" ? 'selected' : ''; ?>>coffee</option>
<option value="fa-cog" <?php echo esc_attr( $item->fa_icon ) == "fa-cog" ? 'selected' : ''; ?>>cog</option>
<option value="fa-cogs" <?php echo esc_attr( $item->fa_icon ) == "fa-cogs" ? 'selected' : ''; ?>>cogs</option>
<option value="fa-columns" <?php echo esc_attr( $item->fa_icon ) == "fa-columns" ? 'selected' : ''; ?>>columns</option>
<option value="fa-comment" <?php echo esc_attr( $item->fa_icon ) == "fa-comment" ? 'selected' : ''; ?>>comment</option>
<option value="fa-comment-o" <?php echo esc_attr( $item->fa_icon ) == "fa-comment-o" ? 'selected' : ''; ?>>comment-o</option>
<option value="fa-comments" <?php echo esc_attr( $item->fa_icon ) == "fa-comments" ? 'selected' : ''; ?>>comments</option>
<option value="fa-comments-o" <?php echo esc_attr( $item->fa_icon ) == "fa-comments-o" ? 'selected' : ''; ?>>comments-o</option>
<option value="fa-compass" <?php echo esc_attr( $item->fa_icon ) == "fa-compass" ? 'selected' : ''; ?>>compass</option>
<option value="fa-compress" <?php echo esc_attr( $item->fa_icon ) == "fa-compress" ? 'selected' : ''; ?>>compress</option>
<option value="fa-copy" <?php echo esc_attr( $item->fa_icon ) == "fa-copy" ? 'selected' : ''; ?>>copy</option>
<option value="fa-copyright" <?php echo esc_attr( $item->fa_icon ) == "fa-copyright" ? 'selected' : ''; ?>>copyright</option>
<option value="fa-credit-card" <?php echo esc_attr( $item->fa_icon ) == "fa-credit-card" ? 'selected' : ''; ?>>credit-card</option>
<option value="fa-crop" <?php echo esc_attr( $item->fa_icon ) == "fa-crop" ? 'selected' : ''; ?>>crop</option>
<option value="fa-crosshairs" <?php echo esc_attr( $item->fa_icon ) == "fa-crosshairs" ? 'selected' : ''; ?>>crosshairs</option>
<option value="fa-css3" <?php echo esc_attr( $item->fa_icon ) == "fa-css3" ? 'selected' : ''; ?>>css3</option>
<option value="fa-cube" <?php echo esc_attr( $item->fa_icon ) == "fa-cube" ? 'selected' : ''; ?>>cube</option>
<option value="fa-cubes" <?php echo esc_attr( $item->fa_icon ) == "fa-cubes" ? 'selected' : ''; ?>>cubes</option>
<option value="fa-cut" <?php echo esc_attr( $item->fa_icon ) == "fa-cut" ? 'selected' : ''; ?>>cut</option>
<option value="fa-cutlery" <?php echo esc_attr( $item->fa_icon ) == "fa-cutlery" ? 'selected' : ''; ?>>cutlery</option>
<option value="fa-dashboard" <?php echo esc_attr( $item->fa_icon ) == "fa-dashboard" ? 'selected' : ''; ?>>dashboard</option>
<option value="fa-database" <?php echo esc_attr( $item->fa_icon ) == "fa-database" ? 'selected' : ''; ?>>database</option>
<option value="fa-dedent" <?php echo esc_attr( $item->fa_icon ) == "fa-dedent" ? 'selected' : ''; ?>>dedent</option>
<option value="fa-delicious" <?php echo esc_attr( $item->fa_icon ) == "fa-delicious" ? 'selected' : ''; ?>>delicious</option>
<option value="fa-desktop" <?php echo esc_attr( $item->fa_icon ) == "fa-desktop" ? 'selected' : ''; ?>>desktop</option>
<option value="fa-deviantart" <?php echo esc_attr( $item->fa_icon ) == "fa-deviantart" ? 'selected' : ''; ?>>deviantart</option>
<option value="fa-digg" <?php echo esc_attr( $item->fa_icon ) == "fa-digg" ? 'selected' : ''; ?>>digg</option>
<option value="fa-dollar" <?php echo esc_attr( $item->fa_icon ) == "fa-dollar" ? 'selected' : ''; ?>>dollar</option>
<option value="fa-dot-circle-o" <?php echo esc_attr( $item->fa_icon ) == "fa-dot-circle-o" ? 'selected' : ''; ?>>dot-circle-o</option>
<option value="fa-download" <?php echo esc_attr( $item->fa_icon ) == "fa-download" ? 'selected' : ''; ?>>download</option>
<option value="fa-dribbble" <?php echo esc_attr( $item->fa_icon ) == "fa-dribbble" ? 'selected' : ''; ?>>dribbble</option>
<option value="fa-dropbox" <?php echo esc_attr( $item->fa_icon ) == "fa-dropbox" ? 'selected' : ''; ?>>dropbox</option>
<option value="fa-drupal" <?php echo esc_attr( $item->fa_icon ) == "fa-drupal" ? 'selected' : ''; ?>>drupal</option>
<option value="fa-edit" <?php echo esc_attr( $item->fa_icon ) == "fa-edit" ? 'selected' : ''; ?>>edit</option>
<option value="fa-eject" <?php echo esc_attr( $item->fa_icon ) == "fa-eject" ? 'selected' : ''; ?>>eject</option>
<option value="fa-ellipsis-h" <?php echo esc_attr( $item->fa_icon ) == "fa-ellipsis-h" ? 'selected' : ''; ?>>ellipsis-h</option>
<option value="fa-ellipsis-v" <?php echo esc_attr( $item->fa_icon ) == "fa-ellipsis-v" ? 'selected' : ''; ?>>ellipsis-v</option>
<option value="fa-empire" <?php echo esc_attr( $item->fa_icon ) == "fa-empire" ? 'selected' : ''; ?>>empire</option>
<option value="fa-envelope" <?php echo esc_attr( $item->fa_icon ) == "fa-envelope" ? 'selected' : ''; ?>>envelope</option>
<option value="fa-envelope-o" <?php echo esc_attr( $item->fa_icon ) == "fa-envelope-o" ? 'selected' : ''; ?>>envelope-o</option>
<option value="fa-envelope-square" <?php echo esc_attr( $item->fa_icon ) == "fa-envelope-square" ? 'selected' : ''; ?>>envelope-square</option>
<option value="fa-eraser" <?php echo esc_attr( $item->fa_icon ) == "fa-eraser" ? 'selected' : ''; ?>>eraser</option>
<option value="fa-eur" <?php echo esc_attr( $item->fa_icon ) == "fa-eur" ? 'selected' : ''; ?>>eur</option>
<option value="fa-euro" <?php echo esc_attr( $item->fa_icon ) == "fa-euro" ? 'selected' : ''; ?>>euro</option>
<option value="fa-exchange" <?php echo esc_attr( $item->fa_icon ) == "fa-exchange" ? 'selected' : ''; ?>>exchange</option>
<option value="fa-exclamation" <?php echo esc_attr( $item->fa_icon ) == "fa-exclamation" ? 'selected' : ''; ?>>exclamation</option>
<option value="fa-exclamation-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-exclamation-circle" ? 'selected' : ''; ?>>exclamation-circle</option>
<option value="fa-exclamation-triangle" <?php echo esc_attr( $item->fa_icon ) == "fa-exclamation-triangle" ? 'selected' : ''; ?>>exclamation-triangle</option>
<option value="fa-expand" <?php echo esc_attr( $item->fa_icon ) == "fa-expand" ? 'selected' : ''; ?>>expand</option>
<option value="fa-external-link" <?php echo esc_attr( $item->fa_icon ) == "fa-external-link" ? 'selected' : ''; ?>>external-link</option>
<option value="fa-external-link-square" <?php echo esc_attr( $item->fa_icon ) == "fa-external-link-square" ? 'selected' : ''; ?>>external-link-square</option>
<option value="fa-eye" <?php echo esc_attr( $item->fa_icon ) == "fa-eye" ? 'selected' : ''; ?>>eye</option>
<option value="fa-eye-slash" <?php echo esc_attr( $item->fa_icon ) == "fa-eye-slash" ? 'selected' : ''; ?>>eye-slash</option>
<option value="fa-eyedropper" <?php echo esc_attr( $item->fa_icon ) == "fa-eyedropper" ? 'selected' : ''; ?>>eyedropper</option>
<option value="fa-facebook" <?php echo esc_attr( $item->fa_icon ) == "fa-facebook" ? 'selected' : ''; ?>>facebook</option>
<option value="fa-facebook-square" <?php echo esc_attr( $item->fa_icon ) == "fa-facebook-square" ? 'selected' : ''; ?>>facebook-square</option>
<option value="fa-fast-backward" <?php echo esc_attr( $item->fa_icon ) == "fa-fast-backward" ? 'selected' : ''; ?>>fast-backward</option>
<option value="fa-fast-forward" <?php echo esc_attr( $item->fa_icon ) == "fa-fast-forward" ? 'selected' : ''; ?>>fast-forward</option>
<option value="fa-fax" <?php echo esc_attr( $item->fa_icon ) == "fa-fax" ? 'selected' : ''; ?>>fax</option>
<option value="fa-female" <?php echo esc_attr( $item->fa_icon ) == "fa-female" ? 'selected' : ''; ?>>female</option>
<option value="fa-fighter-jet" <?php echo esc_attr( $item->fa_icon ) == "fa-fighter-jet" ? 'selected' : ''; ?>>fighter-jet</option>
<option value="fa-file" <?php echo esc_attr( $item->fa_icon ) == "fa-file" ? 'selected' : ''; ?>>file</option>
<option value="fa-file-archive-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-archive-o" ? 'selected' : ''; ?>>file-archive-o</option>
<option value="fa-file-audio-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-audio-o" ? 'selected' : ''; ?>>file-audio-o</option>
<option value="fa-file-code-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-code-o" ? 'selected' : ''; ?>>file-code-o</option>
<option value="fa-file-excel-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-excel-o" ? 'selected' : ''; ?>>file-excel-o</option>
<option value="fa-file-image-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-image-o" ? 'selected' : ''; ?>>file-image-o</option>
<option value="fa-file-movie-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-movie-o" ? 'selected' : ''; ?>>file-movie-o</option>
<option value="fa-file-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-o" ? 'selected' : ''; ?>>file-o</option>
<option value="fa-file-pdf-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-pdf-o" ? 'selected' : ''; ?>>file-pdf-o</option>
<option value="fa-file-photo-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-photo-o" ? 'selected' : ''; ?>>file-photo-o</option>
<option value="fa-file-picture-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-picture-o" ? 'selected' : ''; ?>>file-picture-o</option>
<option value="fa-file-powerpoint-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-powerpoint-o" ? 'selected' : ''; ?>>file-powerpoint-o</option>
<option value="fa-file-sound-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-sound-o" ? 'selected' : ''; ?>>file-sound-o</option>
<option value="fa-file-text" <?php echo esc_attr( $item->fa_icon ) == "fa-file-text" ? 'selected' : ''; ?>>file-text</option>
<option value="fa-file-text-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-text-o" ? 'selected' : ''; ?>>file-text-o</option>
<option value="fa-file-video-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-video-o" ? 'selected' : ''; ?>>file-video-o</option>
<option value="fa-file-word-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-word-o" ? 'selected' : ''; ?>>file-word-o</option>
<option value="fa-file-zip-o" <?php echo esc_attr( $item->fa_icon ) == "fa-file-zip-o" ? 'selected' : ''; ?>>file-zip-o</option>
<option value="fa-files-o" <?php echo esc_attr( $item->fa_icon ) == "fa-files-o" ? 'selected' : ''; ?>>files-o</option>
<option value="fa-film" <?php echo esc_attr( $item->fa_icon ) == "fa-film" ? 'selected' : ''; ?>>film</option>
<option value="fa-filter" <?php echo esc_attr( $item->fa_icon ) == "fa-filter" ? 'selected' : ''; ?>>filter</option>
<option value="fa-fire" <?php echo esc_attr( $item->fa_icon ) == "fa-fire" ? 'selected' : ''; ?>>fire</option>
<option value="fa-fire-extinguisher" <?php echo esc_attr( $item->fa_icon ) == "fa-fire-extinguisher" ? 'selected' : ''; ?>>fire-extinguisher</option>
<option value="fa-flag" <?php echo esc_attr( $item->fa_icon ) == "fa-flag" ? 'selected' : ''; ?>>flag</option>
<option value="fa-flag-checkered" <?php echo esc_attr( $item->fa_icon ) == "fa-flag-checkered" ? 'selected' : ''; ?>>flag-checkered</option>
<option value="fa-flag-o" <?php echo esc_attr( $item->fa_icon ) == "fa-flag-o" ? 'selected' : ''; ?>>flag-o</option>
<option value="fa-flash" <?php echo esc_attr( $item->fa_icon ) == "fa-flash" ? 'selected' : ''; ?>>flash</option>
<option value="fa-flask" <?php echo esc_attr( $item->fa_icon ) == "fa-flask" ? 'selected' : ''; ?>>flask</option>
<option value="fa-flickr" <?php echo esc_attr( $item->fa_icon ) == "fa-flickr" ? 'selected' : ''; ?>>flickr</option>
<option value="fa-floppy-o" <?php echo esc_attr( $item->fa_icon ) == "fa-floppy-o" ? 'selected' : ''; ?>>floppy-o</option>
<option value="fa-folder" <?php echo esc_attr( $item->fa_icon ) == "fa-folder" ? 'selected' : ''; ?>>folder</option>
<option value="fa-folder-o" <?php echo esc_attr( $item->fa_icon ) == "fa-folder-o" ? 'selected' : ''; ?>>folder-o</option>
<option value="fa-folder-open" <?php echo esc_attr( $item->fa_icon ) == "fa-folder-open" ? 'selected' : ''; ?>>folder-open</option>
<option value="fa-folder-open-o" <?php echo esc_attr( $item->fa_icon ) == "fa-folder-open-o" ? 'selected' : ''; ?>>folder-open-o</option>
<option value="fa-font" <?php echo esc_attr( $item->fa_icon ) == "fa-font" ? 'selected' : ''; ?>>font</option>
<option value="fa-forward" <?php echo esc_attr( $item->fa_icon ) == "fa-forward" ? 'selected' : ''; ?>>forward</option>
<option value="fa-foursquare" <?php echo esc_attr( $item->fa_icon ) == "fa-foursquare" ? 'selected' : ''; ?>>foursquare</option>
<option value="fa-frown-o" <?php echo esc_attr( $item->fa_icon ) == "fa-frown-o" ? 'selected' : ''; ?>>frown-o</option>
<option value="fa-futbol-o" <?php echo esc_attr( $item->fa_icon ) == "fa-futbol-o" ? 'selected' : ''; ?>>futbol-o</option>
<option value="fa-gamepad" <?php echo esc_attr( $item->fa_icon ) == "fa-gamepad" ? 'selected' : ''; ?>>gamepad</option>
<option value="fa-gavel" <?php echo esc_attr( $item->fa_icon ) == "fa-gavel" ? 'selected' : ''; ?>>gavel</option>
<option value="fa-gbp" <?php echo esc_attr( $item->fa_icon ) == "fa-gbp" ? 'selected' : ''; ?>>gbp</option>
<option value="fa-ge" <?php echo esc_attr( $item->fa_icon ) == "fa-ge" ? 'selected' : ''; ?>>ge</option>
<option value="fa-gear" <?php echo esc_attr( $item->fa_icon ) == "fa-gear" ? 'selected' : ''; ?>>gear</option>
<option value="fa-gears" <?php echo esc_attr( $item->fa_icon ) == "fa-gears" ? 'selected' : ''; ?>>gears</option>
<option value="fa-gift" <?php echo esc_attr( $item->fa_icon ) == "fa-gift" ? 'selected' : ''; ?>>gift</option>
<option value="fa-git" <?php echo esc_attr( $item->fa_icon ) == "fa-git" ? 'selected' : ''; ?>>git</option>
<option value="fa-git-square" <?php echo esc_attr( $item->fa_icon ) == "fa-git-square" ? 'selected' : ''; ?>>git-square</option>
<option value="fa-github" <?php echo esc_attr( $item->fa_icon ) == "fa-github" ? 'selected' : ''; ?>>github</option>
<option value="fa-github-alt" <?php echo esc_attr( $item->fa_icon ) == "fa-github-alt" ? 'selected' : ''; ?>>github-alt</option>
<option value="fa-github-square" <?php echo esc_attr( $item->fa_icon ) == "fa-github-square" ? 'selected' : ''; ?>>github-square</option>
<option value="fa-gittip" <?php echo esc_attr( $item->fa_icon ) == "fa-gittip" ? 'selected' : ''; ?>>gittip</option>
<option value="fa-glass" <?php echo esc_attr( $item->fa_icon ) == "fa-glass" ? 'selected' : ''; ?>>glass</option>
<option value="fa-globe" <?php echo esc_attr( $item->fa_icon ) == "fa-globe" ? 'selected' : ''; ?>>globe</option>
<option value="fa-google" <?php echo esc_attr( $item->fa_icon ) == "fa-google" ? 'selected' : ''; ?>>google</option>
<option value="fa-google-plus" <?php echo esc_attr( $item->fa_icon ) == "fa-google-plus" ? 'selected' : ''; ?>>google-plus</option>
<option value="fa-google-plus-square" <?php echo esc_attr( $item->fa_icon ) == "fa-google-plus-square" ? 'selected' : ''; ?>>google-plus-square</option>
<option value="fa-google-wallet" <?php echo esc_attr( $item->fa_icon ) == "fa-google-wallet" ? 'selected' : ''; ?>>google-wallet</option>
<option value="fa-graduation-cap" <?php echo esc_attr( $item->fa_icon ) == "fa-graduation-cap" ? 'selected' : ''; ?>>graduation-cap</option>
<option value="fa-group" <?php echo esc_attr( $item->fa_icon ) == "fa-group" ? 'selected' : ''; ?>>group</option>
<option value="fa-h-square" <?php echo esc_attr( $item->fa_icon ) == "fa-h-square" ? 'selected' : ''; ?>>h-square</option>
<option value="fa-hacker-news" <?php echo esc_attr( $item->fa_icon ) == "fa-hacker-news" ? 'selected' : ''; ?>>hacker-news</option>
<option value="fa-hand-o-down" <?php echo esc_attr( $item->fa_icon ) == "fa-hand-o-down" ? 'selected' : ''; ?>>hand-o-down</option>
<option value="fa-hand-o-left" <?php echo esc_attr( $item->fa_icon ) == "fa-hand-o-left" ? 'selected' : ''; ?>>hand-o-left</option>
<option value="fa-hand-o-right" <?php echo esc_attr( $item->fa_icon ) == "fa-hand-o-right" ? 'selected' : ''; ?>>hand-o-right</option>
<option value="fa-hand-o-up" <?php echo esc_attr( $item->fa_icon ) == "fa-hand-o-up" ? 'selected' : ''; ?>>hand-o-up</option>
<option value="fa-hdd-o" <?php echo esc_attr( $item->fa_icon ) == "fa-hdd-o" ? 'selected' : ''; ?>>hdd-o</option>
<option value="fa-header" <?php echo esc_attr( $item->fa_icon ) == "fa-header" ? 'selected' : ''; ?>>header</option>
<option value="fa-headphones" <?php echo esc_attr( $item->fa_icon ) == "fa-headphones" ? 'selected' : ''; ?>>headphones</option>
<option value="fa-heart" <?php echo esc_attr( $item->fa_icon ) == "fa-heart" ? 'selected' : ''; ?>>heart</option>
<option value="fa-heart-o" <?php echo esc_attr( $item->fa_icon ) == "fa-heart-o" ? 'selected' : ''; ?>>heart-o</option>
<option value="fa-history" <?php echo esc_attr( $item->fa_icon ) == "fa-history" ? 'selected' : ''; ?>>history</option>
<option value="fa-home" <?php echo esc_attr( $item->fa_icon ) == "fa-home" ? 'selected' : ''; ?>>home</option>
<option value="fa-hospital-o" <?php echo esc_attr( $item->fa_icon ) == "fa-hospital-o" ? 'selected' : ''; ?>>hospital-o</option>
<option value="fa-html5" <?php echo esc_attr( $item->fa_icon ) == "fa-html5" ? 'selected' : ''; ?>>html5</option>
<option value="fa-ils" <?php echo esc_attr( $item->fa_icon ) == "fa-ils" ? 'selected' : ''; ?>>ils</option>
<option value="fa-image" <?php echo esc_attr( $item->fa_icon ) == "fa-image" ? 'selected' : ''; ?>>image</option>
<option value="fa-inbox" <?php echo esc_attr( $item->fa_icon ) == "fa-inbox" ? 'selected' : ''; ?>>inbox</option>
<option value="fa-indent" <?php echo esc_attr( $item->fa_icon ) == "fa-indent" ? 'selected' : ''; ?>>indent</option>
<option value="fa-info" <?php echo esc_attr( $item->fa_icon ) == "fa-info" ? 'selected' : ''; ?>>info</option>
<option value="fa-info-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-info-circle" ? 'selected' : ''; ?>>info-circle</option>
<option value="fa-inr" <?php echo esc_attr( $item->fa_icon ) == "fa-inr" ? 'selected' : ''; ?>>inr</option>
<option value="fa-instagram" <?php echo esc_attr( $item->fa_icon ) == "fa-instagram" ? 'selected' : ''; ?>>instagram</option>
<option value="fa-institution" <?php echo esc_attr( $item->fa_icon ) == "fa-institution" ? 'selected' : ''; ?>>institution</option>
<option value="fa-ioxhost" <?php echo esc_attr( $item->fa_icon ) == "fa-ioxhost" ? 'selected' : ''; ?>>ioxhost</option>
<option value="fa-italic" <?php echo esc_attr( $item->fa_icon ) == "fa-italic" ? 'selected' : ''; ?>>italic</option>
<option value="fa-joomla" <?php echo esc_attr( $item->fa_icon ) == "fa-joomla" ? 'selected' : ''; ?>>joomla</option>
<option value="fa-jpy" <?php echo esc_attr( $item->fa_icon ) == "fa-jpy" ? 'selected' : ''; ?>>jpy</option>
<option value="fa-jsfiddle" <?php echo esc_attr( $item->fa_icon ) == "fa-jsfiddle" ? 'selected' : ''; ?>>jsfiddle</option>
<option value="fa-key" <?php echo esc_attr( $item->fa_icon ) == "fa-key" ? 'selected' : ''; ?>>key</option>
<option value="fa-keyboard-o" <?php echo esc_attr( $item->fa_icon ) == "fa-keyboard-o" ? 'selected' : ''; ?>>keyboard-o</option>
<option value="fa-krw" <?php echo esc_attr( $item->fa_icon ) == "fa-krw" ? 'selected' : ''; ?>>krw</option>
<option value="fa-language" <?php echo esc_attr( $item->fa_icon ) == "fa-language" ? 'selected' : ''; ?>>language</option>
<option value="fa-laptop" <?php echo esc_attr( $item->fa_icon ) == "fa-laptop" ? 'selected' : ''; ?>>laptop</option>
<option value="fa-lastfm" <?php echo esc_attr( $item->fa_icon ) == "fa-lastfm" ? 'selected' : ''; ?>>lastfm</option>
<option value="fa-lastfm-square" <?php echo esc_attr( $item->fa_icon ) == "fa-lastfm-square" ? 'selected' : ''; ?>>lastfm-square</option>
<option value="fa-leaf" <?php echo esc_attr( $item->fa_icon ) == "fa-leaf" ? 'selected' : ''; ?>>leaf</option>
<option value="fa-legal" <?php echo esc_attr( $item->fa_icon ) == "fa-legal" ? 'selected' : ''; ?>>legal</option>
<option value="fa-lemon-o" <?php echo esc_attr( $item->fa_icon ) == "fa-lemon-o" ? 'selected' : ''; ?>>lemon-o</option>
<option value="fa-level-down" <?php echo esc_attr( $item->fa_icon ) == "fa-level-down" ? 'selected' : ''; ?>>level-down</option>
<option value="fa-level-up" <?php echo esc_attr( $item->fa_icon ) == "fa-level-up" ? 'selected' : ''; ?>>level-up</option>
<option value="fa-life-bouy" <?php echo esc_attr( $item->fa_icon ) == "fa-life-bouy" ? 'selected' : ''; ?>>life-bouy</option>
<option value="fa-life-buoy" <?php echo esc_attr( $item->fa_icon ) == "fa-life-buoy" ? 'selected' : ''; ?>>life-buoy</option>
<option value="fa-life-ring" <?php echo esc_attr( $item->fa_icon ) == "fa-life-ring" ? 'selected' : ''; ?>>life-ring</option>
<option value="fa-life-saver" <?php echo esc_attr( $item->fa_icon ) == "fa-life-saver" ? 'selected' : ''; ?>>life-saver</option>
<option value="fa-lightbulb-o" <?php echo esc_attr( $item->fa_icon ) == "fa-lightbulb-o" ? 'selected' : ''; ?>>lightbulb-o</option>
<option value="fa-line-chart" <?php echo esc_attr( $item->fa_icon ) == "fa-line-chart" ? 'selected' : ''; ?>>line-chart</option>
<option value="fa-link" <?php echo esc_attr( $item->fa_icon ) == "fa-link" ? 'selected' : ''; ?>>link</option>
<option value="fa-linkedin" <?php echo esc_attr( $item->fa_icon ) == "fa-linkedin" ? 'selected' : ''; ?>>linkedin</option>
<option value="fa-linkedin-square" <?php echo esc_attr( $item->fa_icon ) == "fa-linkedin-square" ? 'selected' : ''; ?>>linkedin-square</option>
<option value="fa-linux" <?php echo esc_attr( $item->fa_icon ) == "fa-linux" ? 'selected' : ''; ?>>linux</option>
<option value="fa-list" <?php echo esc_attr( $item->fa_icon ) == "fa-list" ? 'selected' : ''; ?>>list</option>
<option value="fa-list-alt" <?php echo esc_attr( $item->fa_icon ) == "fa-list-alt" ? 'selected' : ''; ?>>list-alt</option>
<option value="fa-list-ol" <?php echo esc_attr( $item->fa_icon ) == "fa-list-ol" ? 'selected' : ''; ?>>list-ol</option>
<option value="fa-list-ul" <?php echo esc_attr( $item->fa_icon ) == "fa-list-ul" ? 'selected' : ''; ?>>list-ul</option>
<option value="fa-location-arrow" <?php echo esc_attr( $item->fa_icon ) == "fa-location-arrow" ? 'selected' : ''; ?>>location-arrow</option>
<option value="fa-lock" <?php echo esc_attr( $item->fa_icon ) == "fa-lock" ? 'selected' : ''; ?>>lock</option>
<option value="fa-long-arrow-down" <?php echo esc_attr( $item->fa_icon ) == "fa-long-arrow-down" ? 'selected' : ''; ?>>long-arrow-down</option>
<option value="fa-long-arrow-left" <?php echo esc_attr( $item->fa_icon ) == "fa-long-arrow-left" ? 'selected' : ''; ?>>long-arrow-left</option>
<option value="fa-long-arrow-right" <?php echo esc_attr( $item->fa_icon ) == "fa-long-arrow-right" ? 'selected' : ''; ?>>long-arrow-right</option>
<option value="fa-long-arrow-up" <?php echo esc_attr( $item->fa_icon ) == "fa-long-arrow-up" ? 'selected' : ''; ?>>long-arrow-up</option>
<option value="fa-magic" <?php echo esc_attr( $item->fa_icon ) == "fa-magic" ? 'selected' : ''; ?>>magic</option>
<option value="fa-magnet" <?php echo esc_attr( $item->fa_icon ) == "fa-magnet" ? 'selected' : ''; ?>>magnet</option>
<option value="fa-mail-forward" <?php echo esc_attr( $item->fa_icon ) == "fa-mail-forward" ? 'selected' : ''; ?>>mail-forward</option>
<option value="fa-mail-reply" <?php echo esc_attr( $item->fa_icon ) == "fa-mail-reply" ? 'selected' : ''; ?>>mail-reply</option>
<option value="fa-mail-reply-all" <?php echo esc_attr( $item->fa_icon ) == "fa-mail-reply-all" ? 'selected' : ''; ?>>mail-reply-all</option>
<option value="fa-male" <?php echo esc_attr( $item->fa_icon ) == "fa-male" ? 'selected' : ''; ?>>male</option>
<option value="fa-map-marker" <?php echo esc_attr( $item->fa_icon ) == "fa-map-marker" ? 'selected' : ''; ?>>map-marker</option>
<option value="fa-maxcdn" <?php echo esc_attr( $item->fa_icon ) == "fa-maxcdn" ? 'selected' : ''; ?>>maxcdn</option>
<option value="fa-meanpath" <?php echo esc_attr( $item->fa_icon ) == "fa-meanpath" ? 'selected' : ''; ?>>meanpath</option>
<option value="fa-medkit" <?php echo esc_attr( $item->fa_icon ) == "fa-medkit" ? 'selected' : ''; ?>>medkit</option>
<option value="fa-meh-o" <?php echo esc_attr( $item->fa_icon ) == "fa-meh-o" ? 'selected' : ''; ?>>meh-o</option>
<option value="fa-microphone" <?php echo esc_attr( $item->fa_icon ) == "fa-microphone" ? 'selected' : ''; ?>>microphone</option>
<option value="fa-microphone-slash" <?php echo esc_attr( $item->fa_icon ) == "fa-microphone-slash" ? 'selected' : ''; ?>>microphone-slash</option>
<option value="fa-minus" <?php echo esc_attr( $item->fa_icon ) == "fa-minus" ? 'selected' : ''; ?>>minus</option>
<option value="fa-minus-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-minus-circle" ? 'selected' : ''; ?>>minus-circle</option>
<option value="fa-minus-square" <?php echo esc_attr( $item->fa_icon ) == "fa-minus-square" ? 'selected' : ''; ?>>minus-square</option>
<option value="fa-minus-square-o" <?php echo esc_attr( $item->fa_icon ) == "fa-minus-square-o" ? 'selected' : ''; ?>>minus-square-o</option>
<option value="fa-mobile" <?php echo esc_attr( $item->fa_icon ) == "fa-mobile" ? 'selected' : ''; ?>>mobile</option>
<option value="fa-mobile-phone" <?php echo esc_attr( $item->fa_icon ) == "fa-mobile-phone" ? 'selected' : ''; ?>>mobile-phone</option>
<option value="fa-money" <?php echo esc_attr( $item->fa_icon ) == "fa-money" ? 'selected' : ''; ?>>money</option>
<option value="fa-moon-o" <?php echo esc_attr( $item->fa_icon ) == "fa-moon-o" ? 'selected' : ''; ?>>moon-o</option>
<option value="fa-mortar-board" <?php echo esc_attr( $item->fa_icon ) == "fa-mortar-board" ? 'selected' : ''; ?>>mortar-board</option>
<option value="fa-music" <?php echo esc_attr( $item->fa_icon ) == "fa-music" ? 'selected' : ''; ?>>music</option>
<option value="fa-navicon" <?php echo esc_attr( $item->fa_icon ) == "fa-navicon" ? 'selected' : ''; ?>>navicon</option>
<option value="fa-newspaper-o" <?php echo esc_attr( $item->fa_icon ) == "fa-newspaper-o" ? 'selected' : ''; ?>>newspaper-o</option>
<option value="fa-openid" <?php echo esc_attr( $item->fa_icon ) == "fa-openid" ? 'selected' : ''; ?>>openid</option>
<option value="fa-outdent" <?php echo esc_attr( $item->fa_icon ) == "fa-outdent" ? 'selected' : ''; ?>>outdent</option>
<option value="fa-pagelines" <?php echo esc_attr( $item->fa_icon ) == "fa-pagelines" ? 'selected' : ''; ?>>pagelines</option>
<option value="fa-paint-brush" <?php echo esc_attr( $item->fa_icon ) == "fa-paint-brush" ? 'selected' : ''; ?>>paint-brush</option>
<option value="fa-paper-plane" <?php echo esc_attr( $item->fa_icon ) == "fa-paper-plane" ? 'selected' : ''; ?>>paper-plane</option>
<option value="fa-paper-plane-o" <?php echo esc_attr( $item->fa_icon ) == "fa-paper-plane-o" ? 'selected' : ''; ?>>paper-plane-o</option>
<option value="fa-paperclip" <?php echo esc_attr( $item->fa_icon ) == "fa-paperclip" ? 'selected' : ''; ?>>paperclip</option>
<option value="fa-paragraph" <?php echo esc_attr( $item->fa_icon ) == "fa-paragraph" ? 'selected' : ''; ?>>paragraph</option>
<option value="fa-paste" <?php echo esc_attr( $item->fa_icon ) == "fa-paste" ? 'selected' : ''; ?>>paste</option>
<option value="fa-pause" <?php echo esc_attr( $item->fa_icon ) == "fa-pause" ? 'selected' : ''; ?>>pause</option>
<option value="fa-paw" <?php echo esc_attr( $item->fa_icon ) == "fa-paw" ? 'selected' : ''; ?>>paw</option>
<option value="fa-paypal" <?php echo esc_attr( $item->fa_icon ) == "fa-paypal" ? 'selected' : ''; ?>>paypal</option>
<option value="fa-pencil" <?php echo esc_attr( $item->fa_icon ) == "fa-pencil" ? 'selected' : ''; ?>>pencil</option>
<option value="fa-pencil-square" <?php echo esc_attr( $item->fa_icon ) == "fa-pencil-square" ? 'selected' : ''; ?>>pencil-square</option>
<option value="fa-pencil-square-o" <?php echo esc_attr( $item->fa_icon ) == "fa-pencil-square-o" ? 'selected' : ''; ?>>pencil-square-o</option>
<option value="fa-phone" <?php echo esc_attr( $item->fa_icon ) == "fa-phone" ? 'selected' : ''; ?>>phone</option>
<option value="fa-phone-square" <?php echo esc_attr( $item->fa_icon ) == "fa-phone-square" ? 'selected' : ''; ?>>phone-square</option>
<option value="fa-photo" <?php echo esc_attr( $item->fa_icon ) == "fa-photo" ? 'selected' : ''; ?>>photo</option>
<option value="fa-picture-o" <?php echo esc_attr( $item->fa_icon ) == "fa-picture-o" ? 'selected' : ''; ?>>picture-o</option>
<option value="fa-pie-chart" <?php echo esc_attr( $item->fa_icon ) == "fa-pie-chart" ? 'selected' : ''; ?>>pie-chart</option>
<option value="fa-pied-piper" <?php echo esc_attr( $item->fa_icon ) == "fa-pied-piper" ? 'selected' : ''; ?>>pied-piper</option>
<option value="fa-pied-piper-alt" <?php echo esc_attr( $item->fa_icon ) == "fa-pied-piper-alt" ? 'selected' : ''; ?>>pied-piper-alt</option>
<option value="fa-pinterest" <?php echo esc_attr( $item->fa_icon ) == "fa-pinterest" ? 'selected' : ''; ?>>pinterest</option>
<option value="fa-pinterest-square" <?php echo esc_attr( $item->fa_icon ) == "fa-pinterest-square" ? 'selected' : ''; ?>>pinterest-square</option>
<option value="fa-plane" <?php echo esc_attr( $item->fa_icon ) == "fa-plane" ? 'selected' : ''; ?>>plane</option>
<option value="fa-play" <?php echo esc_attr( $item->fa_icon ) == "fa-play" ? 'selected' : ''; ?>>play</option>
<option value="fa-play-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-play-circle" ? 'selected' : ''; ?>>play-circle</option>
<option value="fa-play-circle-o" <?php echo esc_attr( $item->fa_icon ) == "fa-play-circle-o" ? 'selected' : ''; ?>>play-circle-o</option>
<option value="fa-plug" <?php echo esc_attr( $item->fa_icon ) == "fa-plug" ? 'selected' : ''; ?>>plug</option>
<option value="fa-plus" <?php echo esc_attr( $item->fa_icon ) == "fa-plus" ? 'selected' : ''; ?>>plus</option>
<option value="fa-plus-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-plus-circle" ? 'selected' : ''; ?>>plus-circle</option>
<option value="fa-plus-square" <?php echo esc_attr( $item->fa_icon ) == "fa-plus-square" ? 'selected' : ''; ?>>plus-square</option>
<option value="fa-plus-square-o" <?php echo esc_attr( $item->fa_icon ) == "fa-plus-square-o" ? 'selected' : ''; ?>>plus-square-o</option>
<option value="fa-power-off" <?php echo esc_attr( $item->fa_icon ) == "fa-power-off" ? 'selected' : ''; ?>>power-off</option>
<option value="fa-print" <?php echo esc_attr( $item->fa_icon ) == "fa-print" ? 'selected' : ''; ?>>print</option>
<option value="fa-puzzle-piece" <?php echo esc_attr( $item->fa_icon ) == "fa-puzzle-piece" ? 'selected' : ''; ?>>puzzle-piece</option>
<option value="fa-qq" <?php echo esc_attr( $item->fa_icon ) == "fa-qq" ? 'selected' : ''; ?>>qq</option>
<option value="fa-qrcode" <?php echo esc_attr( $item->fa_icon ) == "fa-qrcode" ? 'selected' : ''; ?>>qrcode</option>
<option value="fa-question" <?php echo esc_attr( $item->fa_icon ) == "fa-question" ? 'selected' : ''; ?>>question</option>
<option value="fa-question-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-question-circle" ? 'selected' : ''; ?>>question-circle</option>
<option value="fa-quote-left" <?php echo esc_attr( $item->fa_icon ) == "fa-quote-left" ? 'selected' : ''; ?>>quote-left</option>
<option value="fa-quote-right" <?php echo esc_attr( $item->fa_icon ) == "fa-quote-right" ? 'selected' : ''; ?>>quote-right</option>
<option value="fa-ra" <?php echo esc_attr( $item->fa_icon ) == "fa-ra" ? 'selected' : ''; ?>>ra</option>
<option value="fa-random" <?php echo esc_attr( $item->fa_icon ) == "fa-random" ? 'selected' : ''; ?>>random</option>
<option value="fa-rebel" <?php echo esc_attr( $item->fa_icon ) == "fa-rebel" ? 'selected' : ''; ?>>rebel</option>
<option value="fa-recycle" <?php echo esc_attr( $item->fa_icon ) == "fa-recycle" ? 'selected' : ''; ?>>recycle</option>
<option value="fa-reddit" <?php echo esc_attr( $item->fa_icon ) == "fa-reddit" ? 'selected' : ''; ?>>reddit</option>
<option value="fa-reddit-square" <?php echo esc_attr( $item->fa_icon ) == "fa-reddit-square" ? 'selected' : ''; ?>>reddit-square</option>
<option value="fa-refresh" <?php echo esc_attr( $item->fa_icon ) == "fa-refresh" ? 'selected' : ''; ?>>refresh</option>
<option value="fa-remove" <?php echo esc_attr( $item->fa_icon ) == "fa-remove" ? 'selected' : ''; ?>>remove</option>
<option value="fa-renren" <?php echo esc_attr( $item->fa_icon ) == "fa-renren" ? 'selected' : ''; ?>>renren</option>
<option value="fa-reorder" <?php echo esc_attr( $item->fa_icon ) == "fa-reorder" ? 'selected' : ''; ?>>reorder</option>
<option value="fa-repeat" <?php echo esc_attr( $item->fa_icon ) == "fa-repeat" ? 'selected' : ''; ?>>repeat</option>
<option value="fa-reply" <?php echo esc_attr( $item->fa_icon ) == "fa-reply" ? 'selected' : ''; ?>>reply</option>
<option value="fa-reply-all" <?php echo esc_attr( $item->fa_icon ) == "fa-reply-all" ? 'selected' : ''; ?>>reply-all</option>
<option value="fa-retweet" <?php echo esc_attr( $item->fa_icon ) == "fa-retweet" ? 'selected' : ''; ?>>retweet</option>
<option value="fa-rmb" <?php echo esc_attr( $item->fa_icon ) == "fa-rmb" ? 'selected' : ''; ?>>rmb</option>
<option value="fa-road" <?php echo esc_attr( $item->fa_icon ) == "fa-road" ? 'selected' : ''; ?>>road</option>
<option value="fa-rocket" <?php echo esc_attr( $item->fa_icon ) == "fa-rocket" ? 'selected' : ''; ?>>rocket</option>
<option value="fa-rotate-left" <?php echo esc_attr( $item->fa_icon ) == "fa-rotate-left" ? 'selected' : ''; ?>>rotate-left</option>
<option value="fa-rotate-right" <?php echo esc_attr( $item->fa_icon ) == "fa-rotate-right" ? 'selected' : ''; ?>>rotate-right</option>
<option value="fa-rouble" <?php echo esc_attr( $item->fa_icon ) == "fa-rouble" ? 'selected' : ''; ?>>rouble</option>
<option value="fa-rss" <?php echo esc_attr( $item->fa_icon ) == "fa-rss" ? 'selected' : ''; ?>>rss</option>
<option value="fa-rss-square" <?php echo esc_attr( $item->fa_icon ) == "fa-rss-square" ? 'selected' : ''; ?>>rss-square</option>
<option value="fa-rub" <?php echo esc_attr( $item->fa_icon ) == "fa-rub" ? 'selected' : ''; ?>>rub</option>
<option value="fa-ruble" <?php echo esc_attr( $item->fa_icon ) == "fa-ruble" ? 'selected' : ''; ?>>ruble</option>
<option value="fa-rupee" <?php echo esc_attr( $item->fa_icon ) == "fa-rupee" ? 'selected' : ''; ?>>rupee</option>
<option value="fa-save" <?php echo esc_attr( $item->fa_icon ) == "fa-save" ? 'selected' : ''; ?>>save</option>
<option value="fa-scissors" <?php echo esc_attr( $item->fa_icon ) == "fa-scissors" ? 'selected' : ''; ?>>scissors</option>
<option value="fa-search" <?php echo esc_attr( $item->fa_icon ) == "fa-search" ? 'selected' : ''; ?>>search</option>
<option value="fa-search-minus" <?php echo esc_attr( $item->fa_icon ) == "fa-search-minus" ? 'selected' : ''; ?>>search-minus</option>
<option value="fa-search-plus" <?php echo esc_attr( $item->fa_icon ) == "fa-search-plus" ? 'selected' : ''; ?>>search-plus</option>
<option value="fa-send" <?php echo esc_attr( $item->fa_icon ) == "fa-send" ? 'selected' : ''; ?>>send</option>
<option value="fa-send-o" <?php echo esc_attr( $item->fa_icon ) == "fa-send-o" ? 'selected' : ''; ?>>send-o</option>
<option value="fa-share" <?php echo esc_attr( $item->fa_icon ) == "fa-share" ? 'selected' : ''; ?>>share</option>
<option value="fa-share-alt" <?php echo esc_attr( $item->fa_icon ) == "fa-share-alt" ? 'selected' : ''; ?>>share-alt</option>
<option value="fa-share-alt-square" <?php echo esc_attr( $item->fa_icon ) == "fa-share-alt-square" ? 'selected' : ''; ?>>share-alt-square</option>
<option value="fa-share-square" <?php echo esc_attr( $item->fa_icon ) == "fa-share-square" ? 'selected' : ''; ?>>share-square</option>
<option value="fa-share-square-o" <?php echo esc_attr( $item->fa_icon ) == "fa-share-square-o" ? 'selected' : ''; ?>>share-square-o</option>
<option value="fa-shekel" <?php echo esc_attr( $item->fa_icon ) == "fa-shekel" ? 'selected' : ''; ?>>shekel</option>
<option value="fa-sheqel" <?php echo esc_attr( $item->fa_icon ) == "fa-sheqel" ? 'selected' : ''; ?>>sheqel</option>
<option value="fa-shield" <?php echo esc_attr( $item->fa_icon ) == "fa-shield" ? 'selected' : ''; ?>>shield</option>
<option value="fa-shopping-cart" <?php echo esc_attr( $item->fa_icon ) == "fa-shopping-cart" ? 'selected' : ''; ?>>shopping-cart</option>
<option value="fa-sign-in" <?php echo esc_attr( $item->fa_icon ) == "fa-sign-in" ? 'selected' : ''; ?>>sign-in</option>
<option value="fa-sign-out" <?php echo esc_attr( $item->fa_icon ) == "fa-sign-out" ? 'selected' : ''; ?>>sign-out</option>
<option value="fa-signal" <?php echo esc_attr( $item->fa_icon ) == "fa-signal" ? 'selected' : ''; ?>>signal</option>
<option value="fa-sitemap" <?php echo esc_attr( $item->fa_icon ) == "fa-sitemap" ? 'selected' : ''; ?>>sitemap</option>
<option value="fa-skype" <?php echo esc_attr( $item->fa_icon ) == "fa-skype" ? 'selected' : ''; ?>>skype</option>
<option value="fa-slack" <?php echo esc_attr( $item->fa_icon ) == "fa-slack" ? 'selected' : ''; ?>>slack</option>
<option value="fa-sliders" <?php echo esc_attr( $item->fa_icon ) == "fa-sliders" ? 'selected' : ''; ?>>sliders</option>
<option value="fa-slideshare" <?php echo esc_attr( $item->fa_icon ) == "fa-slideshare" ? 'selected' : ''; ?>>slideshare</option>
<option value="fa-smile-o" <?php echo esc_attr( $item->fa_icon ) == "fa-smile-o" ? 'selected' : ''; ?>>smile-o</option>
<option value="fa-soccer-ball-o" <?php echo esc_attr( $item->fa_icon ) == "fa-soccer-ball-o" ? 'selected' : ''; ?>>soccer-ball-o</option>
<option value="fa-sort" <?php echo esc_attr( $item->fa_icon ) == "fa-sort" ? 'selected' : ''; ?>>sort</option>
<option value="fa-sort-alpha-asc" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-alpha-asc" ? 'selected' : ''; ?>>sort-alpha-asc</option>
<option value="fa-sort-alpha-desc" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-alpha-desc" ? 'selected' : ''; ?>>sort-alpha-desc</option>
<option value="fa-sort-amount-asc" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-amount-asc" ? 'selected' : ''; ?>>sort-amount-asc</option>
<option value="fa-sort-amount-desc" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-amount-desc" ? 'selected' : ''; ?>>sort-amount-desc</option>
<option value="fa-sort-asc" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-asc" ? 'selected' : ''; ?>>sort-asc</option>
<option value="fa-sort-desc" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-desc" ? 'selected' : ''; ?>>sort-desc</option>
<option value="fa-sort-down" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-down" ? 'selected' : ''; ?>>sort-down</option>
<option value="fa-sort-numeric-asc" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-numeric-asc" ? 'selected' : ''; ?>>sort-numeric-asc</option>
<option value="fa-sort-numeric-desc" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-numeric-desc" ? 'selected' : ''; ?>>sort-numeric-desc</option>
<option value="fa-sort-up" <?php echo esc_attr( $item->fa_icon ) == "fa-sort-up" ? 'selected' : ''; ?>>sort-up</option>
<option value="fa-soundcloud" <?php echo esc_attr( $item->fa_icon ) == "fa-soundcloud" ? 'selected' : ''; ?>>soundcloud</option>
<option value="fa-space-shuttle" <?php echo esc_attr( $item->fa_icon ) == "fa-space-shuttle" ? 'selected' : ''; ?>>space-shuttle</option>
<option value="fa-spinner" <?php echo esc_attr( $item->fa_icon ) == "fa-spinner" ? 'selected' : ''; ?>>spinner</option>
<option value="fa-spoon" <?php echo esc_attr( $item->fa_icon ) == "fa-spoon" ? 'selected' : ''; ?>>spoon</option>
<option value="fa-spotify" <?php echo esc_attr( $item->fa_icon ) == "fa-spotify" ? 'selected' : ''; ?>>spotify</option>
<option value="fa-square" <?php echo esc_attr( $item->fa_icon ) == "fa-square" ? 'selected' : ''; ?>>square</option>
<option value="fa-square-o" <?php echo esc_attr( $item->fa_icon ) == "fa-square-o" ? 'selected' : ''; ?>>square-o</option>
<option value="fa-stack-exchange" <?php echo esc_attr( $item->fa_icon ) == "fa-stack-exchange" ? 'selected' : ''; ?>>stack-exchange</option>
<option value="fa-stack-overflow" <?php echo esc_attr( $item->fa_icon ) == "fa-stack-overflow" ? 'selected' : ''; ?>>stack-overflow</option>
<option value="fa-star" <?php echo esc_attr( $item->fa_icon ) == "fa-star" ? 'selected' : ''; ?>>star</option>
<option value="fa-star-half" <?php echo esc_attr( $item->fa_icon ) == "fa-star-half" ? 'selected' : ''; ?>>star-half</option>
<option value="fa-star-half-empty" <?php echo esc_attr( $item->fa_icon ) == "fa-star-half-empty" ? 'selected' : ''; ?>>star-half-empty</option>
<option value="fa-star-half-full" <?php echo esc_attr( $item->fa_icon ) == "fa-star-half-full" ? 'selected' : ''; ?>>star-half-full</option>
<option value="fa-star-half-o" <?php echo esc_attr( $item->fa_icon ) == "fa-star-half-o" ? 'selected' : ''; ?>>star-half-o</option>
<option value="fa-star-o" <?php echo esc_attr( $item->fa_icon ) == "fa-star-o" ? 'selected' : ''; ?>>star-o</option>
<option value="fa-steam" <?php echo esc_attr( $item->fa_icon ) == "fa-steam" ? 'selected' : ''; ?>>steam</option>
<option value="fa-steam-square" <?php echo esc_attr( $item->fa_icon ) == "fa-steam-square" ? 'selected' : ''; ?>>steam-square</option>
<option value="fa-step-backward" <?php echo esc_attr( $item->fa_icon ) == "fa-step-backward" ? 'selected' : ''; ?>>step-backward</option>
<option value="fa-step-forward" <?php echo esc_attr( $item->fa_icon ) == "fa-step-forward" ? 'selected' : ''; ?>>step-forward</option>
<option value="fa-stethoscope" <?php echo esc_attr( $item->fa_icon ) == "fa-stethoscope" ? 'selected' : ''; ?>>stethoscope</option>
<option value="fa-stop" <?php echo esc_attr( $item->fa_icon ) == "fa-stop" ? 'selected' : ''; ?>>stop</option>
<option value="fa-strikethrough" <?php echo esc_attr( $item->fa_icon ) == "fa-strikethrough" ? 'selected' : ''; ?>>strikethrough</option>
<option value="fa-stumbleupon" <?php echo esc_attr( $item->fa_icon ) == "fa-stumbleupon" ? 'selected' : ''; ?>>stumbleupon</option>
<option value="fa-stumbleupon-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-stumbleupon-circle" ? 'selected' : ''; ?>>stumbleupon-circle</option>
<option value="fa-subscript" <?php echo esc_attr( $item->fa_icon ) == "fa-subscript" ? 'selected' : ''; ?>>subscript</option>
<option value="fa-suitcase" <?php echo esc_attr( $item->fa_icon ) == "fa-suitcase" ? 'selected' : ''; ?>>suitcase</option>
<option value="fa-sun-o" <?php echo esc_attr( $item->fa_icon ) == "fa-sun-o" ? 'selected' : ''; ?>>sun-o</option>
<option value="fa-superscript" <?php echo esc_attr( $item->fa_icon ) == "fa-superscript" ? 'selected' : ''; ?>>superscript</option>
<option value="fa-support" <?php echo esc_attr( $item->fa_icon ) == "fa-support" ? 'selected' : ''; ?>>support</option>
<option value="fa-table" <?php echo esc_attr( $item->fa_icon ) == "fa-table" ? 'selected' : ''; ?>>table</option>
<option value="fa-tablet" <?php echo esc_attr( $item->fa_icon ) == "fa-tablet" ? 'selected' : ''; ?>>tablet</option>
<option value="fa-tachometer" <?php echo esc_attr( $item->fa_icon ) == "fa-tachometer" ? 'selected' : ''; ?>>tachometer</option>
<option value="fa-tag" <?php echo esc_attr( $item->fa_icon ) == "fa-tag" ? 'selected' : ''; ?>>tag</option>
<option value="fa-tags" <?php echo esc_attr( $item->fa_icon ) == "fa-tags" ? 'selected' : ''; ?>>tags</option>
<option value="fa-tasks" <?php echo esc_attr( $item->fa_icon ) == "fa-tasks" ? 'selected' : ''; ?>>tasks</option>
<option value="fa-taxi" <?php echo esc_attr( $item->fa_icon ) == "fa-taxi" ? 'selected' : ''; ?>>taxi</option>
<option value="fa-tencent-weibo" <?php echo esc_attr( $item->fa_icon ) == "fa-tencent-weibo" ? 'selected' : ''; ?>>tencent-weibo</option>
<option value="fa-terminal" <?php echo esc_attr( $item->fa_icon ) == "fa-terminal" ? 'selected' : ''; ?>>terminal</option>
<option value="fa-text-height" <?php echo esc_attr( $item->fa_icon ) == "fa-text-height" ? 'selected' : ''; ?>>text-height</option>
<option value="fa-text-width" <?php echo esc_attr( $item->fa_icon ) == "fa-text-width" ? 'selected' : ''; ?>>text-width</option>
<option value="fa-th" <?php echo esc_attr( $item->fa_icon ) == "fa-th" ? 'selected' : ''; ?>>th</option>
<option value="fa-th-large" <?php echo esc_attr( $item->fa_icon ) == "fa-th-large" ? 'selected' : ''; ?>>th-large</option>
<option value="fa-th-list" <?php echo esc_attr( $item->fa_icon ) == "fa-th-list" ? 'selected' : ''; ?>>th-list</option>
<option value="fa-thumb-tack" <?php echo esc_attr( $item->fa_icon ) == "fa-thumb-tack" ? 'selected' : ''; ?>>thumb-tack</option>
<option value="fa-thumbs-down" <?php echo esc_attr( $item->fa_icon ) == "fa-thumbs-down" ? 'selected' : ''; ?>>thumbs-down</option>
<option value="fa-thumbs-o-down" <?php echo esc_attr( $item->fa_icon ) == "fa-thumbs-o-down" ? 'selected' : ''; ?>>thumbs-o-down</option>
<option value="fa-thumbs-o-up" <?php echo esc_attr( $item->fa_icon ) == "fa-thumbs-o-up" ? 'selected' : ''; ?>>thumbs-o-up</option>
<option value="fa-thumbs-up" <?php echo esc_attr( $item->fa_icon ) == "fa-thumbs-up" ? 'selected' : ''; ?>>thumbs-up</option>
<option value="fa-ticket" <?php echo esc_attr( $item->fa_icon ) == "fa-ticket" ? 'selected' : ''; ?>>ticket</option>
<option value="fa-times" <?php echo esc_attr( $item->fa_icon ) == "fa-times" ? 'selected' : ''; ?>>times</option>
<option value="fa-times-circle" <?php echo esc_attr( $item->fa_icon ) == "fa-times-circle" ? 'selected' : ''; ?>>times-circle</option>
<option value="fa-times-circle-o" <?php echo esc_attr( $item->fa_icon ) == "fa-times-circle-o" ? 'selected' : ''; ?>>times-circle-o</option>
<option value="fa-tint" <?php echo esc_attr( $item->fa_icon ) == "fa-tint" ? 'selected' : ''; ?>>tint</option>
<option value="fa-toggle-down" <?php echo esc_attr( $item->fa_icon ) == "fa-toggle-down" ? 'selected' : ''; ?>>toggle-down</option>
<option value="fa-toggle-left" <?php echo esc_attr( $item->fa_icon ) == "fa-toggle-left" ? 'selected' : ''; ?>>toggle-left</option>
<option value="fa-toggle-off" <?php echo esc_attr( $item->fa_icon ) == "fa-toggle-off" ? 'selected' : ''; ?>>toggle-off</option>
<option value="fa-toggle-on" <?php echo esc_attr( $item->fa_icon ) == "fa-toggle-on" ? 'selected' : ''; ?>>toggle-on</option>
<option value="fa-toggle-right" <?php echo esc_attr( $item->fa_icon ) == "fa-toggle-right" ? 'selected' : ''; ?>>toggle-right</option>
<option value="fa-toggle-up" <?php echo esc_attr( $item->fa_icon ) == "fa-toggle-up" ? 'selected' : ''; ?>>toggle-up</option>
<option value="fa-trash" <?php echo esc_attr( $item->fa_icon ) == "fa-trash" ? 'selected' : ''; ?>>trash</option>
<option value="fa-trash-o" <?php echo esc_attr( $item->fa_icon ) == "fa-trash-o" ? 'selected' : ''; ?>>trash-o</option>
<option value="fa-tree" <?php echo esc_attr( $item->fa_icon ) == "fa-tree" ? 'selected' : ''; ?>>tree</option>
<option value="fa-trello" <?php echo esc_attr( $item->fa_icon ) == "fa-trello" ? 'selected' : ''; ?>>trello</option>
<option value="fa-trophy" <?php echo esc_attr( $item->fa_icon ) == "fa-trophy" ? 'selected' : ''; ?>>trophy</option>
<option value="fa-truck" <?php echo esc_attr( $item->fa_icon ) == "fa-truck" ? 'selected' : ''; ?>>truck</option>
<option value="fa-try" <?php echo esc_attr( $item->fa_icon ) == "fa-try" ? 'selected' : ''; ?>>try</option>
<option value="fa-tty" <?php echo esc_attr( $item->fa_icon ) == "fa-tty" ? 'selected' : ''; ?>>tty</option>
<option value="fa-tumblr" <?php echo esc_attr( $item->fa_icon ) == "fa-tumblr" ? 'selected' : ''; ?>>tumblr</option>
<option value="fa-tumblr-square" <?php echo esc_attr( $item->fa_icon ) == "fa-tumblr-square" ? 'selected' : ''; ?>>tumblr-square</option>
<option value="fa-turkish-lira" <?php echo esc_attr( $item->fa_icon ) == "fa-turkish-lira" ? 'selected' : ''; ?>>turkish-lira</option>
<option value="fa-twitch" <?php echo esc_attr( $item->fa_icon ) == "fa-twitch" ? 'selected' : ''; ?>>twitch</option>
<option value="fa-twitter" <?php echo esc_attr( $item->fa_icon ) == "fa-twitter" ? 'selected' : ''; ?>>twitter</option>
<option value="fa-twitter-square" <?php echo esc_attr( $item->fa_icon ) == "fa-twitter-square" ? 'selected' : ''; ?>>twitter-square</option>
<option value="fa-umbrella" <?php echo esc_attr( $item->fa_icon ) == "fa-umbrella" ? 'selected' : ''; ?>>umbrella</option>
<option value="fa-underline" <?php echo esc_attr( $item->fa_icon ) == "fa-underline" ? 'selected' : ''; ?>>underline</option>
<option value="fa-undo" <?php echo esc_attr( $item->fa_icon ) == "fa-undo" ? 'selected' : ''; ?>>undo</option>
<option value="fa-university" <?php echo esc_attr( $item->fa_icon ) == "fa-university" ? 'selected' : ''; ?>>university</option>
<option value="fa-unlink" <?php echo esc_attr( $item->fa_icon ) == "fa-unlink" ? 'selected' : ''; ?>>unlink</option>
<option value="fa-unlock" <?php echo esc_attr( $item->fa_icon ) == "fa-unlock" ? 'selected' : ''; ?>>unlock</option>
<option value="fa-unlock-alt" <?php echo esc_attr( $item->fa_icon ) == "fa-unlock-alt" ? 'selected' : ''; ?>>unlock-alt</option>
<option value="fa-unsorted" <?php echo esc_attr( $item->fa_icon ) == "fa-unsorted" ? 'selected' : ''; ?>>unsorted</option>
<option value="fa-upload" <?php echo esc_attr( $item->fa_icon ) == "fa-upload" ? 'selected' : ''; ?>>upload</option>
<option value="fa-usd" <?php echo esc_attr( $item->fa_icon ) == "fa-usd" ? 'selected' : ''; ?>>usd</option>
<option value="fa-user" <?php echo esc_attr( $item->fa_icon ) == "fa-user" ? 'selected' : ''; ?>>user</option>
<option value="fa-user-md" <?php echo esc_attr( $item->fa_icon ) == "fa-user-md" ? 'selected' : ''; ?>>user-md</option>
<option value="fa-users" <?php echo esc_attr( $item->fa_icon ) == "fa-users" ? 'selected' : ''; ?>>users</option>
<option value="fa-video-camera" <?php echo esc_attr( $item->fa_icon ) == "fa-video-camera" ? 'selected' : ''; ?>>video-camera</option>
<option value="fa-vimeo-square" <?php echo esc_attr( $item->fa_icon ) == "fa-vimeo-square" ? 'selected' : ''; ?>>vimeo-square</option>
<option value="fa-vine" <?php echo esc_attr( $item->fa_icon ) == "fa-vine" ? 'selected' : ''; ?>>vine</option>
<option value="fa-vk" <?php echo esc_attr( $item->fa_icon ) == "fa-vk" ? 'selected' : ''; ?>>vk</option>
<option value="fa-volume-down" <?php echo esc_attr( $item->fa_icon ) == "fa-volume-down" ? 'selected' : ''; ?>>volume-down</option>
<option value="fa-volume-off" <?php echo esc_attr( $item->fa_icon ) == "fa-volume-off" ? 'selected' : ''; ?>>volume-off</option>
<option value="fa-volume-up" <?php echo esc_attr( $item->fa_icon ) == "fa-volume-up" ? 'selected' : ''; ?>>volume-up</option>
<option value="fa-warning" <?php echo esc_attr( $item->fa_icon ) == "fa-warning" ? 'selected' : ''; ?>>warning</option>
<option value="fa-wechat" <?php echo esc_attr( $item->fa_icon ) == "fa-wechat" ? 'selected' : ''; ?>>wechat</option>
<option value="fa-weibo" <?php echo esc_attr( $item->fa_icon ) == "fa-weibo" ? 'selected' : ''; ?>>weibo</option>
<option value="fa-weixin" <?php echo esc_attr( $item->fa_icon ) == "fa-weixin" ? 'selected' : ''; ?>>weixin</option>
<option value="fa-wheelchair" <?php echo esc_attr( $item->fa_icon ) == "fa-wheelchair" ? 'selected' : ''; ?>>wheelchair</option>
<option value="fa-wifi" <?php echo esc_attr( $item->fa_icon ) == "fa-wifi" ? 'selected' : ''; ?>>wifi</option>
<option value="fa-windows" <?php echo esc_attr( $item->fa_icon ) == "fa-windows" ? 'selected' : ''; ?>>windows</option>
<option value="fa-won" <?php echo esc_attr( $item->fa_icon ) == "fa-won" ? 'selected' : ''; ?>>won</option>
<option value="fa-wordpress" <?php echo esc_attr( $item->fa_icon ) == "fa-wordpress" ? 'selected' : ''; ?>>wordpress</option>
<option value="fa-wrench" <?php echo esc_attr( $item->fa_icon ) == "fa-wrench" ? 'selected' : ''; ?>>wrench</option>
<option value="fa-xing" <?php echo esc_attr( $item->fa_icon ) == "fa-xing" ? 'selected' : ''; ?>>xing</option>
<option value="fa-xing-square" <?php echo esc_attr( $item->fa_icon ) == "fa-xing-square" ? 'selected' : ''; ?>>xing-square</option>
<option value="fa-yahoo" <?php echo esc_attr( $item->fa_icon ) == "fa-yahoo" ? 'selected' : ''; ?>>yahoo</option>
<option value="fa-yelp" <?php echo esc_attr( $item->fa_icon ) == "fa-yelp" ? 'selected' : ''; ?>>yelp</option>
<option value="fa-yen" <?php echo esc_attr( $item->fa_icon ) == "fa-yen" ? 'selected' : ''; ?>>yen</option>
<option value="fa-youtube" <?php echo esc_attr( $item->fa_icon ) == "fa-youtube" ? 'selected' : ''; ?>>youtube</option>
<option value="fa-youtube-play" <?php echo esc_attr( $item->fa_icon ) == "fa-youtube-play" ? 'selected' : ''; ?>>youtube-play</option>
<option value="fa-youtube-square" <?php echo esc_attr( $item->fa_icon ) == "fa-youtube-square" ? 'selected' : ''; ?>>youtube-square</option>